### ISSUE TITLE
Tag registering with wrong BI

### ISSUE THREAD

**Issue by zcrysler** [jbrzusto/TO_DO#133]
A tag registration for project 38 is registering with a BI of 19.39, but it should be 9.7.  The recording has pulses every 9.7 seconds, Lotek tag ID 217, it's currently registered as motusTagID 25474.  I uploaded this recording Oct 30, the file is called "proj38tags2.zip", I can re-upload if you'd like

**Comment by jbrzusto** [comment]
This tag's recording for some reason has higher frequency offset variation than we usually see among pulses
within a burst.  Hopefully this is just a burn-in effect, and the tag will stabilize.  If the user wishes to gamble
that this is true, then the record for this tag can be fixed by this query on motus.org's tag database:
```SQL
update tags set period=9.69725 where tagID=25474;
```
where that corrected period came from re-running the tag registration process manually with much looser
parameterization so that all four bursts were considered.

**Comment by cjardine-bsc** [comment]
I've updated the tag record to set the period as 9.96725

**Comment by zcrysler** [comment]
Thanks all!
