### ISSUE TITLE
Unable to upload .DTA files

### ISSUE THREAD

**Issue by zcrysler** [jbrzusto/TO_DO#144]
When you try to upload Lotek .DTA files you get a warnings "Error: Invalid file extension: Wisner_9.DTA".  They're accepted if they're zipped, although I uploaded some last week and never got an email that they were processed

**Comment by zcrysler** [comment]
update: they seem to go through if you zip each .dta file individually, rather than zipping together multiple .dta files into one .zip file - for reference, job IDs 124573, 124565, 124556

**Comment by jbrzusto** [comment]
There are different things going on here:

- the web-browser is disallowing ".DTA" files; that's because I'd forgotten to change the allowed
filetypes on the new upload server.  I have fixed that by this query on the database:
```sql
update uploads.ul_options set value="7Z,7z,DTA,RAR,ZIP,dta,rar,zip"
 where name="allowed_file_types";
```
- files uploaded to the old server should now have been processed on the new server, but
  you won't have received a message about that. You can  search on the status page by log entries, 
  which contain the original file names.
   e.g. next to `Listing shows`, click on the drop-down box and choose `jobs with log matching`
  then enter a filename in the text box to the right and hit `Enter`.

**Comment by zcrysler** [comment]
I thought Firday uploads were being processed on the new server?  The uploads I did this morning had 2/3 process successfully although the hourly plots are blank and I'd be surprised if no antennas were picked up on either, but I didn't get an email about any of them either.

**Comment by jbrzusto** [comment]
All uploads to this point should now have been processed on the new server, but if they were processed
there *after* being uploaded to the old server (sensorgnome.org/upload) and then transferred under-the-hood by me, you won't have received an email.  

I'm filing "I didn't get an email about any of them either." as a new issue: #147; can you fill in a relevant
job ID there?

Thanks!

**Comment by jbrzusto** [comment]
Closing this, as .DTA files can now be uploaded individually.
