### ISSUE TITLE
Data not pushed to motus server SG-2616BBBK1111

### ISSUE THREAD

**Issue by zcrysler** [jbrzusto/TO_DO#179]
Hourly plots show data between August - Sept 15 2017 with detections, but there is no data available through the motus server

**Comment by jbrzusto** [comment]
This is due to a failed `exportData` subjob here: https://sgdata.motus.org/status?jobID=129549

**Comment by jbrzusto** [comment]
Retried this job; it failed due to the now closed issue https://github.com/jbrzusto/motusServer/issues/350

**Comment by jbrzusto** [comment]
There are other jobs which failed due to this error and which have not been subsequently
exported correctly:

 - [ ] 112427 | SG-1215BBBK1796
 - [ ] 112454 | SG-1D53RPI333CD
 - [ ] 114279 | SG-F072RPI36609
 - [ ] 115175 | SG-1315BBBK0078
 - [ ] 115295 | SG-5D8DRPI22FBE
 - [ ] 117979 | SG-1914BBBK0893
 - [ ] 118099 | SG-1215BBBK1793
 - [ ] 118101 | SG-1315BBBK0120
 - [ ] 119800 | SG-2916BBBK0751
 - [ ] 120115 | SG-1914BBBK0856
 - [ ] 120127 | SG-1914BBBK0833
 - [ ] 120142 | SG-1914BBBK0873
 - [ ] 122324 | SG-1634RPI38648
 - [ ] 122339 | SG-5541RPI3E7F8
 - [ ] 122589 | SG-1914BBBK0887
 - [ ] 122812 | SG-CCD3RPI30FD2
 - [ ] 125435 | SG-D7D1RPI33164
