### ISSUE TITLE
Upload errors project 120

### ISSUE THREAD

**Issue by zcrysler** [jbrzusto/TO_DO#180]
A large number of uploads for project 120 got processing errors last night, they all seem to get errors with SGfindtags for receiver SG-0816BBBK0C16:

160744 | SGfindtags | 2018-03-08 21:52:28.978Z | Error | serno = SG-0816BBBK0C16; monoBN = 244; canResume = true
-- | -- | -- | -- | --
160745 | SGfindtags | 2018-03-08 21:52:29.015Z | Error | serno = SG-0816BBBK0C16; monoBN = 245; canResume = false

Can these be re-run?

**Comment by jbrzusto** [comment]
These failed due to a bug I introduced yesterday and fixed today.
But as a separate item, users should be upload all files for a given receiver in a single archive.
(At least not in separate archives at the same time.)  So that way, a single main job is run to
process the files, not a whole bunch.  And there may still be a bug if multiple uploads for the
same receiver happen at the same time:  jbrzusto/motusServer#341
Can you suggest improvements to the wording of the instructions on the [upload page](https://sgdata.motus.org/upload) to make it more clear to users that they shouldn't do this?

**Comment by jbrzusto** [comment]
That receiver is being rerun:  https://sgdata.motus.org?jobID=160919

**Comment by zcrysler** [comment]
What about replacing 
"Please do not upload sensorgnome .txt/.gz files individually and please do keep all files from a receiver together in the same archive"
with
"Please do not upload sensorgnome .txt/.gz files individually, and please do keep all files from a receiver together in the same archive, ie. zip together all daily files within the SGdata folder"

**Comment by jbrzusto** [comment]
Here's what I went with:

```
ie. make one big zip file that includes all days of data from your SG
```
