### ISSUE TITLE
verify or fix sites in /SG/contrib/2016 with files from multiple receivers

### ISSUE THREAD

**Issue by jbrzusto** [jbrzusto/TO_DO#25]
Please check off when resolved and append explanation
---
- [x] CTRiver/Sugarloaf 1614BBBK1911
- [x] CTRiver/Sugarloaf 1614BBBK1911_1
Special case; receiver got augmented  serial number to distinguish it from Motus/PtLepreau
---
- [x] Motus/BlackRock 4005BBBK2390
- [x] Motus/BlackRock 4000BBBK9170
Okay; two diffferent receivers used.
---
- [x] Motus/Blandford 4002BBBK1530
- [x] Motus/Blandford 1614BBBK1889
Okay; two diffferent receivers used.
---
- [x] Motus/Cambridge 5113BBBK3100
- [x] Motus/Cambridge 4005BBBK3760   **Fixed**: 3760 was Anderson
---
- [x] Motus/Escuminac 1614BBBK1660
- [x] Motus/Escuminac 4001BBBK2310
Okay; 2 different recvs.
---
- [x] Motus/Exeter 5113BBBK3182
- [x] Motus/Exeter 5113BBBK2827
Okay; 2 different recvs
---
- [x] Motus/Formosa 3615BBBK1E34  **Fixed** this is site Mildmay; files moved and sites reprocessed
- [x] Motus/Formosa 5113BBBK3084
---
- [x] Motus/HighIsland 3214BBBK8447 **Fixed**: files in August are from BSC troubleshooting
- [x] Motus/HighIsland 3214BBBK8453   **Fixed**: should be GrandIsleLA
---
- [x] Motus/Huggins 51012BB01207
- [x] Motus/Huggins 1012BB012075
- [x] Motus/Huggins 4002BBBK0170
Okay; 3 different recvs.
---
- [x] Motus/Koffler 3214BBBK6103
- [x] Motus/Koffler 5113BBBK3182 **Fixed**: should be Exeter
---
- [x] Motus/Langford 5113BBBK3182
- [x] Motus/Langford 5113BBBK2827
Okay; 2 recvs;
---
- [x] Motus/OldCut 5113BBBK2972
- [x] Motus/OldCut 1613BBBK2198 **Fixed**; files removed.
---
- [x] Motus/PortMaitland 4001BBBK6020
- [x] Motus/PortMaitland 5113BBBK2799 **Fixed**; files removed
---
- [x] Quebec/JardinEst 5113BBBK0555 **Fixed**; files removed
- [x] Quebec/JardinEst 5113BBBK3168
---
- [x] Quebec/JardinOuest 5113BBBK3168 **Fixed**; files removed
- [x] Quebec/JardinOuest 5113BBBK0555
---
- [x] Quebec/Mobile 5113BBBK2662
- [x] Quebec/Mobile 1614BBBK1878
- [x] Quebec/Mobile 3214BBBK6514
Okay; 3 recvs used

**Comment by StuMackenzie** [comment]
Lots of SG swapping early in the season due to failed units/units that wouldn't connect.

This may be more of an ongoing issue/list opposed to a complete fix, but here's a start. This of course assumes that all the deployment details are up to date and accurate. I'll send this list to Zoe and Dave so they can confirm. Thanks.

3214BBBK8453 - was at Grand Isle moved to Duluth
Huggins - no record of site name (.)?
Motus/Huggins 51012BB01207 - not in Motus database
Motus/Huggins 1012BB012075 - Taylor 2013 deployment VSEA - not elsewhere in database
Motus/Huggins 4002BBBK0170 - deployed in 2015 - Middle Ohio2
Motus/OldCut 1613BBBK2198 - not in database 
Motus/PortMaitland 4001BBBK6020 - not in database 

Quebec - 2016 deployment data not up to date, so I can't tell

**Comment by zcrysler** [comment]
I can't check off any boxes but here are the issues for the Quebec data:

Quebec/JardinEst 5113BBBK0555 - was deployed in 2016 at FM Jardin Ouest
Quebec/JardinOuest 5113BBBK3168 - was deployed in 2016 at FM Jardin Est
Quebec/Mobile 5113BBBK2662 - was deployed in 2016 at FM Tour Jutras Demo
