### ISSUE TITLE
Acadian Whimbrel tag transfer

### ISSUE THREAD

**Issue by zcrysler** [jbrzusto/TO_DO#78]
The following tags need to be moved from project "78. Acadian Peninsula - Whimbrel" with Julie Paquet, to project "129 University of Oklahoma" with Jeremy Ross.

498, 500, 501, 502, 503

all with burst rate 5.29, dateBin 2016-3

They've already been moved on motus.org

**Comment by jbrzusto** [comment]
That should be all it takes.  Whenever the SG server runs data from a receiver, it grabs
all tag metadata from motus.  So the next time we do a full re-run of all receiver data, those tags will appear under the correct project.

Also, the SG server supplies detections of motus tag IDs, and that's not affected by which
project the tag is assigned to.  So really, it's only the metadata on motus that need to change, since
the linking between a tag ID and a project is done either there, or on a user's computer (once the user
R package is done).
