### ISSUE TITLE
Failed tag registration - project 103

### ISSUE THREAD

**Issue by zcrysler** [jbrzusto/TO_DO#91]
I've uploaded a couple different recordings for tag 490 in project 103, each time I upload I get the message that the the burst rate can't be estimated.  Is this likely a problem with the tag itself or should I continue asking the user for new recordings of it?

**Comment by jbrzusto** [comment]
The recording I looked at shows this tag's pulse offset frequency is
more variable than typical, and the transmitter is sometimes on for
~80 samples instead of the typical 120.  This might reduce tag
detectability somewhat.  Given the current availability of tags, it's
still worth deploying this one, so I've registered it, but I  would 
deploy it last, in case it turns out not to be needed.

---

Logs of failed attempts to register this tag:

```SQL
sqlite> select t1.id, json_extract(t1.data, "$.log") from jobs as t1 join jobs as t2
 on t1.id=t2.stump where t2.type="registerTags" and t1.data glob "*103*490*"
 order by t1.id desc limit 6;
```
360612|Job 360612 with 1 pending subjobs entered processing queue #1
Unpacking file zcrysler:2017-05-31T20-52-47.742:proj_103_tag490_reg.zip with unzip -o
Archive:  /sgm/queue/1//00360612/upload/zcrysler:2017-05-31T20-52-47.742:proj_103_tag490_reg.zip
  inflating: tag490.wav
   creating: __MACOSX/
...
  inflating: __MACOSX/._tag490.wav
  inflating: tagreg.txt
  inflating: __MACOSX/._tagreg.txt
Deleted 2 junk files with names like
   /sgm/queue/1//00360612/00360617/__MACOSX/._tag490.wav
Only 1 detection of id 490 found in file tag490.wav, so I can't estimate burst interval.

360070|Job 360070 with 1 pending subjobs entered processing queue #1
Unpacking file zcrysler:2017-05-30T19-16-29.270:proj_103_NYC_Audubon_nanotags.zip with unzip -o
Archive:  /sgm/queue/1//00360070/upload/zcrysler:2017-05-30T19-16-29.270:proj_103_NYC_Audubon_nanotags.zip
  inflating: tag490.wav
   creating: __MACOSX/
...
  inflating: __MACOSX/._tag490.wav
  inflating: tagreg.txt
  inflating: __MACOSX/._tagreg.txt
Deleted 2 junk files with names like
   /sgm/queue/1//00360070/00360322/__MACOSX/._tag490.wav
No tags detected in file tag490.wav

347524|Job 347524 with 1 pending subjobs entered processing queue #3
Unpacking file zcrysler:2017-05-24T22-42-24.885:project103tagregistration.zip with unzip -o
Archive:  /sgm/queue/3//00347524/upload/zcrysler:2017-05-24T22-42-24.885:project103tagregistration.zip
  inflating: tag490.wav
   creating: __MACOSX/
...
  inflating: __MACOSX/._tag490.wav
  inflating: tagreg.txt
  inflating: __MACOSX/._tagreg.txt
Deleted 2 junk files with names like
   /sgm/queue/3//00347524/00347530/__MACOSX/._tag490.wav
Unable to get a good estimate of burst interval for tag id 490 in file tag490.wav
Please re-record this tag and re-upload

344135|Job 344135 with 1 pending subjobs entered processing queue #3
Unpacking file selbin:2017-05-22T20-59-33.887:tagreg4.zip with unzip -o
Archive:  /sgm/queue/3//00344135/upload/selbin:2017-05-22T20-59-33.887:tagreg4.zip
  inflating: tag490.wav
 extracting: tagreg.txt
...
Archive:  /sgm/queue/3//00344135/upload/selbin:2017-05-22T20-59-33.887:tagreg4.zip
  inflating: tag490.wav
 extracting: tagreg.txt
Unable to get a good estimate of burst interval for tag id 490 in file tag490.wav
Please re-record this tag and re-upload

326816|Job 326816 with 1 pending subjobs entered processing queue #2
Unpacking file zcrysler:2017-05-15T21-47-15.538:103_tag_registrations.zip with unzip -o
Archive:  /sgm/queue/2//00326816/upload/zcrysler:2017-05-15T21-47-15.538:103_tag_registrations.zip
  inflating: tag490.wav
   creating: __MACOSX/
...
  inflating: __MACOSX/._tag490.wav
  inflating: tagreg.txt
  inflating: __MACOSX/._tagreg.txt
Deleted 2 junk files with names like
   /sgm/queue/2//00326816/00326821/__MACOSX/._tag490.wav
Only 1 detection of id 490 found in file tag490.wav, so I can't estimate burst interval.

326301|Job 326301 with 1 pending subjobs entered processing queue #4
Unpacking file selbin:2017-05-15T15-09-35.283:tagreg3.zip with unzip -o
Archive:  /sgm/queue/4//00326301/upload/selbin:2017-05-15T15-09-35.283:tagreg3.zip
 extracting: tagreg.txt
  inflating: tag490.wav
...
Archive:  /sgm/queue/4//00326301/upload/selbin:2017-05-15T15-09-35.283:tagreg3.zip
 extracting: tagreg.txt
  inflating: tag490.wav
Only 1 detection of id 490 found in file tag490.wav, so I can't estimate burst interval.
```
